apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-events
  namespace: argo
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    example:
      owner: "sumin7kim"
      repository: "argo-workflows-local-demo"
      webhook:
        endpoint: "/push"  # 웹훅 URL 경로
        port: "12000"
        method: "POST"
      events:
        - "push"
      apiToken:
        name: github-access
        key: token
      webhookSecret:
        name: github-access
        key: secret